apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: simple-todo-react-app-ec2-cluster
  region: ap-south-1
  version: "1.34"

nodeGroups:
  - name: simple-todo-react-app-ec2-node-group
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    minSize: 2
    maxSize: 3
    labels:
      role: app
      env: dev
    ssh:
      allow: false